name: Rust application

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ['stable', 'beta', 'nightly']
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt -qq update
          sudo apt install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake binutils-dev libiberty-dev libmysqlclient-dev libpq-dev libsqlite3-dev
          rustup install ${{matrix.rust_version }}
          rustup default ${{matrix.rust_version }}
          cargo install diesel_cli
      - name: Check builds
        run: |
          cargo build --features mysql
          cargo build --features postgres
          cargo build --features sqlite
        env:
          RUSTFLAGS: '-C link-dead-code -L /usr/local/lib'
      - name: Run integration tests
        run: |
          ./run_tests.sh
        env:
          RUSTFLAGS: '-C link-dead-code -L /usr/local/lib'
      - name: Run coverage
        run: |
          ./run_coverage.sh
        env:
          RUSTFLAGS: '-C link-dead-code -L /usr/local/lib'
